package main

import (
	"sort"
	"strings"

	"singbox-launcher/core/config/registry"
)

// renderIndex — оглавление: версия контракта и ядра, три ступени конвейера,
// список схем со ссылками, суб-схемы, коды.
func renderIndex(raw *rawRegistry, reg *registry.Registry, schemes []string) string {
	var b strings.Builder
	b.WriteString("# Контракт узла: схемы, поля, коды / Node contract: schemes, fields, codes\n\n")
	b.WriteString("<!-- Сгенерировано contract/tools/gendocs. Не редактировать руками: правьте реестр. -->\n")
	b.WriteString("<!-- Generated by contract/tools/gendocs. Do not edit: change the registry instead. -->\n\n")
	b.WriteString("Страницы этого каталога собираются из реестра " +
		"`contract/registry/` командой `go generate ./contract/...`; CI сверяет их " +
		"с реестром на каждом PR. Правки руками стираются следующей генерацией — " +
		"менять надо реестр.\n")
	b.WriteString("_These pages are generated from the `contract/registry/` registry by " +
		"`go generate ./contract/...`, and CI checks them against the registry on every PR. " +
		"Hand edits are overwritten by the next run: change the registry instead._\n\n")

	t := &table{head: []string{"", "Версия / version"}}
	t.add("Контракт / contract (`contract/VERSION`)", code(raw.version))
	t.add("Ядро / core (`body.core`)", coreVersions(reg, schemes))
	t.render(&b)

	b.WriteString("## Конвейер / Pipeline\n\n")
	b.WriteString("Любой вход — share-URI, sing-box или Xray JSON, wg-conf, ручное тело — " +
		"проходит три ступени, одинаковые для лаунчера и LxBox:\n")
	b.WriteString("_Every input — a share URI, sing-box or Xray JSON, a wg-conf, a hand-written " +
		"body — goes through the same three stages in both apps:_\n\n")
	b.WriteString("1. **маппер / mapper** — переводит диалект в канонический путь тела по " +
		"`uri.*.maps_to` и алиасам реестра; значений не проверяет и дефолтов не ставит.\n")
	b.WriteString("   _Translates the dialect into a canonical body path; checks nothing, " +
		"defaults nothing._\n")
	b.WriteString("2. **санитайзер / sanitizer** — по `body`-секциям реестра: тип, enum, формат, " +
		"`allowed_for`/`forbidden_for`, `conflicts`/`requires`; каждое снятие или приведение " +
		"даёт запись в `warnings[]` ([коды / codes](warnings.md)).\n")
	b.WriteString("   _Runs the registry `body` sections; every drop or coercion is recorded._\n")
	b.WriteString("3. **эмиттер / emitter** — сериализация в порядке `body.order`; схемных " +
		"ветвлений в коде нет.\n")
	b.WriteString("   _Serializes in `body.order`; no per-scheme branching in code._\n\n")
	b.WriteString("Нормативное описание — [`contract/docs/CANON.md` §8](../CANON.md#8-конвейер-spec-131).\n")
	b.WriteString("_The normative text is [`contract/docs/CANON.md` §8](../CANON.md#8-конвейер-spec-131)._\n\n")

	b.WriteString("## Схемы / Schemes\n\n")
	st := &table{head: []string{
		"Схема / scheme", "sing-box `type`", "`kind`", "Источники / sources",
		"`extension`", "Ссылка / link form",
	}}
	for _, scheme := range schemes {
		p := raw.protocols[scheme]
		if p == nil {
			continue
		}
		ext := ""
		if p.Extension != nil {
			ext = code(*p.Extension)
		}
		link := "нет / no"
		if p.URI != nil {
			link = "да / yes"
		}
		st.add("[`"+scheme+"`](protocols/"+schemeFileName(scheme)+")",
			code(p.SingboxType), code(p.Kind), codeList(p.Sources), ext, link)
	}
	st.render(&b)

	b.WriteString("## Общие суб-схемы / Shared sub-schemas\n\n")
	sub := &table{head: []string{"Суб-схема / sub-schema", "Что внутри / what is inside"}}
	sub.add("[`tls`](protocols/_tls.md)", "TLS, uTLS, REALITY, ECH — параметры ссылки и поля тела / link parameters and body fields")
	sub.add("[`transports`](protocols/_transports.md)", "варианты транспорта по `transport.type` / transport variants by `transport.type`")
	sub.add("[`multiplex`](protocols/_multiplex.md)", "мультиплексирование потоков / stream multiplexing")
	sub.add("[`dialer`](protocols/_dialer.md)", "общие поля dialer, вливаются в тело плоско / common dialer fields, inlined flat")
	sub.render(&b)

	b.WriteString("## Коды предупреждений / Warning codes\n\n")
	b.WriteString("[`warnings.md`](warnings.md) — словарь кодов: severity, тексты на двух языках " +
		"и обратный индекс «какое поле какой схемы ставит этот код».\n")
	b.WriteString("_[`warnings.md`](warnings.md) is the code dictionary: severity, texts in both " +
		"languages, and a reverse index of which field of which scheme raises each code._\n\n")

	b.WriteString("## Лимиты / Limits\n\n")
	lt := &table{head: []string{"Лимит / limit", "Значение / value", "Примечание / note"}}
	limits := reg.Limits()
	names := make([]string, 0, len(limits))
	for k := range limits {
		names = append(names, k)
	}
	sort.Strings(names)
	for _, n := range names {
		lt.add(code(n), scalar(limits[n].Value), limits[n].Note)
	}
	lt.render(&b)

	return b.String()
}

// coreVersions — версии ядра из `body.core` схем. Обычно она одна на весь
// реестр; если схемы разъехались, страница показывает это, а не прячет.
func coreVersions(reg *registry.Registry, schemes []string) string {
	seen := map[string]bool{}
	for _, s := range schemes {
		if body, ok := reg.Body(s); ok && body.Core != "" {
			seen[body.Core] = true
		}
	}
	return codeList(sortedKeys(seen))
}
