package main

import (
	"sort"
	"strconv"
	"strings"

	"singbox-launcher/core/config/registry"
)

// subPageFile — страница общей суб-схемы, на которую ссылается `ref` в теле.
// Имя файла начинается с подчёркивания: страница не принадлежит ни одной
// схеме, она общая.
var subPageFile = map[string]string{
	"tls":        "_tls.md",
	"transports": "_transports.md",
	"multiplex":  "_multiplex.md",
	"dialer":     "_dialer.md",
}

// renderScheme строит страницу одной схемы. Страница обязана быть
// САМОДОСТАТОЧНОЙ: человек, открывший её из-за одного узла подписки, не
// должен обходить четыре общие суб-схемы, чтобы понять, что с его узлом
// может случиться.
//
// Порядок разделов — от входа к последствиям:
//
//	шапка → Link parameters → Body fields → Diagnosed problems →
//	Replacements → Degradation
//
// Страница английская целиком (решение владельца): `desc_ru`, `text_ru` и
// `impl` в неё не попадают.
func renderScheme(raw *rawRegistry, scheme string, body *registry.BodySchema) string {
	p := raw.protocols[scheme]
	var b strings.Builder

	title := scheme
	if p != nil && p.SingboxType != "" && p.SingboxType != scheme {
		title = scheme + " → " + p.SingboxType
	}
	b.WriteString("# " + title + "\n\n")
	b.WriteString("<!-- Generated by contract/tools/gendocs. Do not edit: change the registry instead. -->\n\n")
	b.WriteString("[← index](../index.md) · [diagnosed problems](../warnings.md)\n\n")

	renderSchemeHeader(&b, p, body)
	renderURIList(&b, raw, p)
	renderBodyList(&b, scheme, body)
	renderSchemeWarnings(&b, raw, scheme, body)
	renderReplacements(&b, raw, scheme, p)
	renderDegradation(&b, scheme, body)
	return b.String()
}

// renderSchemeHeader — маленькая таблица метаданных (две колонки, на экран
// помещается).
func renderSchemeHeader(b *strings.Builder, p *rawProtocol, body *registry.BodySchema) {
	t := &table{head: []string{"Field", "Value"}}
	if p == nil {
		t.add("scheme", "—")
		t.render(b)
		return
	}
	t.add("`scheme`", code(p.Scheme))
	t.add("`singbox_type`", code(p.SingboxType))
	t.add("`kind`", code(p.Kind))
	if len(p.Aliases) > 0 {
		t.add("`aliases`", codeList(aliasNames(p.Aliases)))
	}
	if len(p.Sources) > 0 {
		t.add("`sources`", codeList(p.Sources))
	}
	ext := "—"
	if p.Extension != nil {
		ext = code(*p.Extension)
	}
	t.add("`extension`", ext)
	if body != nil && body.Core != "" {
		t.add("Core the schema was checked against", code(body.Core))
	}
	if p.URI != nil && p.URI.Fragment != "" {
		t.add("URI fragment", code(p.URI.Fragment))
	}
	t.render(b)
}

// renderURIList — параметры ссылки списком. У каждого параметра сразу видно,
// куда он ложится в теле и что будет с негодным значением: правило поля тела
// по адресу maps_to ищется тут же, чтобы человек не прыгал между разделами.
func renderURIList(b *strings.Builder, raw *rawRegistry, p *rawProtocol) {
	b.WriteString("## Link parameters\n\n")
	if p == nil || p.URI == nil {
		b.WriteString("The scheme has no link form: it comes from sing-box JSON only.\n\n")
		return
	}

	l := &list{b: b}
	wrote := false
	if p.URI.Userinfo != nil {
		writeURIItem(l, raw, p.Scheme, "userinfo", p.URI.Userinfo)
		wrote = true
	}
	for _, name := range p.URI.queryOrder {
		if param := p.URI.Query[name]; param != nil {
			writeURIItem(l, raw, p.Scheme, name, param)
			wrote = true
		}
	}
	if !wrote {
		b.WriteString("The scheme carries no query parameters of its own.\n")
	}
	b.WriteString("\n")
	b.WriteString("Shared link parameters live on their own pages: " +
		"[TLS / REALITY](_tls.md#link-parameters), [transports](_transports.md).\n\n")
}

func writeURIItem(l *list, raw *rawRegistry, scheme, name string, p *uriParam) {
	head := "**`" + name + "`**"
	if p.Ext != "" {
		head += " (" + p.Ext + ")"
	}
	l.item(head, p.DescEn)

	if names := aliasNames(p.Aliases); len(names) > 0 {
		l.attr("Also spelled: " + codeList(names))
	}

	// Тип и допустимые значения.
	typ := p.Type
	if len(p.Values) > 0 {
		typ = strings.TrimSpace(typ + ": " + codeList(p.Values))
	}
	if p.Allowlist != "" {
		typ = strings.TrimSpace(typ + " (allowlist `" + p.Allowlist + "`)")
	}
	if p.Meaning != "" && typ == "" {
		typ = code(p.Meaning)
	}
	if p.Validation != "" {
		typ = strings.TrimSpace(typ + " — " + p.Validation)
	}
	def := ""
	if s := scalar(p.Default); s != "" {
		def = "Default: " + s
	}
	if typ != "" {
		l.attr("Type: "+typ, def)
	} else {
		l.attr(def)
	}

	// Куда ложится в теле и что будет с негодным значением.
	paths := p.mapsToPaths()
	if p.DropAlways {
		l.attr("Maps to: nothing — the parameter is always dropped")
	} else if len(paths) > 0 {
		l.attr("Maps to: " + codeList(paths))
		for _, path := range paths {
			if rule := bodyRuleFor(raw, scheme, path); rule != "" {
				l.attr("If invalid: " + rule)
			}
		}
	}
}

// bodyRuleFor — правило поля тела по адресу maps_to, одной строкой. Именно
// оно отвечает на вопрос «а что будет, если в ссылке мусор»: сам параметр
// ссылки решений о значении не принимает (этим занят санитайзер).
func bodyRuleFor(raw *rawRegistry, scheme, path string) string {
	f := raw.bodyField(scheme, path)
	if f == nil {
		return ""
	}
	parts := fieldOutcomes(f, "../")
	if len(parts) == 0 {
		return ""
	}
	return strings.Join(parts, "; ")
}

// renderBodyList — поля тела списком, в порядке body.order. Ссылочные поля
// (`ref`) разворачиваются не здесь, а ниже, в разделе диагностируемых
// проблем: тут достаточно строки со ссылкой на общую страницу.
func renderBodyList(b *strings.Builder, scheme string, body *registry.BodySchema) {
	b.WriteString("## Body fields\n\n")
	if body == nil {
		b.WriteString("No body schema in the registry.\n\n")
		return
	}
	b.WriteString("The path is the one used in the node body.\n\n")
	l := &list{b: b}
	for _, name := range body.Order {
		f := body.Fields[name]
		if f == nil {
			continue
		}
		if file, ok := refPage(name, f); ok {
			l.item("**`"+name+"`**", f.DescEn)
			l.attr("Shared sub-schema: see [" + strings.TrimSuffix(file, ".md") + "](" + file + ")")
			continue
		}
		writeBodyItems(l, "", name, f, "../")
	}
	b.WriteString("\n")
}

// writeBodyItems печатает поле и, для вложенных объектов и вариантов, его
// потомков отдельными пунктами с полным путём.
func writeBodyItems(l *list, prefix, name string, f *registry.Field, linkPrefix string) {
	path := name
	if prefix != "" {
		path = prefix + "." + name
	}
	l.item("**`"+path+"`**", f.DescEn)

	// Тип, ограничения значения.
	l.attr(strings.Join(nonEmpty(bodyType(f), bodyConstraints(f)), ", "))

	// Дефолт и обязательность — одной строкой.
	def := ""
	if s := scalar(f.Default); s != "" {
		def = "Default: " + s
	} else if f.Required {
		def = "Default: none"
	}
	req := ""
	if f.Required {
		req = "Required: yes"
	}
	l.attr(def, req)

	// Что случится с негодным значением.
	for _, o := range fieldOutcomes(f, linkPrefix) {
		l.attr(o)
	}
	// Связи с другими полями.
	for _, r := range fieldRelations(f) {
		l.attr(r)
	}
	if g := bodyGate(f); g != "" {
		l.attr(g)
	}

	if len(f.Variants) > 0 {
		names := make([]string, 0, len(f.Variants))
		for v := range f.Variants {
			names = append(names, v)
		}
		sort.Strings(names)
		for _, v := range names {
			writeNested(l, path+"."+v, f.Variants[v], linkPrefix)
		}
		return
	}
	writeNested(l, path, f, linkPrefix)
}

func writeNested(l *list, path string, f *registry.Field, linkPrefix string) {
	inner := f
	if len(inner.Fields) == 0 && inner.Items != nil {
		inner = inner.Items
	}
	if len(inner.Fields) == 0 {
		return
	}
	order := inner.Order
	if len(order) == 0 {
		for k := range inner.Fields {
			order = append(order, k)
		}
		sort.Strings(order)
	}
	for _, name := range order {
		child := inner.Fields[name]
		if child == nil {
			continue
		}
		writeBodyItems(l, path, name, child, linkPrefix)
	}
}

// fieldOutcomes — что санитайзер делает со значением: действие плюс код.
func fieldOutcomes(f *registry.Field, linkPrefix string) []string {
	var out []string
	if f.OnInvalid != nil {
		out = append(out, "If invalid: "+onInvalidAction(f.OnInvalid)+" → "+
			warnLink(f.OnInvalid.Code, linkPrefix))
	}
	for _, a := range f.Advisory {
		desc := "Accepted with a notice for " + scalarList(a.Values)
		if len(a.Except) > 0 {
			desc = "Accepted with a notice for anything except " + scalarList(a.Except)
		}
		if a.When != nil && a.When.Path != "" {
			desc += ", when `" + a.When.Path + "` is set"
		}
		out = append(out, desc+" → "+warnLink(a.Code, linkPrefix))
	}
	if dw := f.DefaultWhen; dw != nil && dw.Absent {
		line := "If absent: filled in with " + scalar(dw.Value)
		if dw.Code != "" {
			line += " → " + warnLink(dw.Code, linkPrefix)
		}
		out = append(out, line)
	}
	if f.NormalizeCode != "" {
		out = append(out, "If the value had to be cleaned up: "+warnLink(f.NormalizeCode, linkPrefix))
	}
	if f.DropAlways {
		out = append(out, "Always dropped")
	}
	return out
}

// fieldRelations — связи поля со схемой и с другими полями.
func fieldRelations(f *registry.Field) []string {
	var out []string
	if len(f.ForbiddenFor) > 0 {
		out = append(out, "Forbidden for: "+codeList(f.ForbiddenFor))
	}
	if len(f.AllowedFor) > 0 {
		out = append(out, "Only for: "+codeList(f.AllowedFor))
	}
	for _, c := range f.Conflicts {
		out = append(out, "Conflicts with: "+code(c.With))
	}
	for _, rq := range f.Requires {
		req := "Requires: " + code(rq.Path)
		if rq.Equals != nil {
			req += " = " + scalar(rq.Equals)
		}
		out = append(out, req)
	}
	return out
}

func bodyType(f *registry.Field) string {
	typ := f.Type
	if f.Discriminator != "" {
		typ += " (variants by `" + f.Discriminator + "`)"
	}
	if f.Tristate {
		typ += ", tristate"
	}
	if f.Secret {
		typ += ", secret"
	}
	if f.Deprecated {
		typ += ", deprecated"
	}
	if f.Managed {
		typ += ", set by config build"
	}
	if f.AllOrNothing {
		// Формулировка описывает ПОВЕДЕНИЕ ЯДРА, а не действие конвейера:
		// дефолты соседей не дописываются, частичная секция едет как есть
		// (SPEC 131 DRIFT §7.20).
		typ += ", all-or-nothing in the core (setting one field leaves the " +
			"neighbours at zero, i.e. unlimited; a partly filled section is " +
			"passed through unchanged)"
	}
	if typ == "" {
		return ""
	}
	return "Type: " + typ
}

func bodyConstraints(f *registry.Field) string {
	var parts []string
	if len(f.Values) > 0 {
		parts = append(parts, scalarList(f.Values))
	}
	if f.Format != "" {
		parts = append(parts, "format "+code(f.Format))
	}
	if f.Min != nil || f.Max != nil {
		lo, hi := "…", "…"
		if f.Min != nil {
			lo = trimFloat(*f.Min)
		}
		if f.Max != nil {
			hi = trimFloat(*f.Max)
		}
		parts = append(parts, code(lo+"–"+hi))
	}
	if f.Len != nil {
		parts = append(parts, "len "+code(strconv.Itoa(*f.Len)))
	}
	if f.LenParity != "" {
		parts = append(parts, "len "+code(f.LenParity))
	}
	if f.Normalize != "" {
		parts = append(parts, "normalized: "+code(f.Normalize))
	}
	if f.Skip != "" {
		parts = append(parts, "not written by the launcher")
	}
	return strings.Join(parts, ", ")
}

func bodyGate(f *registry.Field) string {
	var parts []string
	if f.MinCore != "" {
		parts = append(parts, "core ≥ "+code(f.MinCore))
	}
	if f.LxOnly {
		parts = append(parts, "lx fork only")
	}
	if f.BuildTag != "" {
		parts = append(parts, "build tag "+code(f.BuildTag))
	}
	if f.Platform != "" {
		parts = append(parts, "OS "+code(f.Platform))
	}
	if len(parts) == 0 {
		return ""
	}
	return "Requires: " + strings.Join(parts, ", ")
}

// refPage говорит, есть ли у ссылочного поля собственная страница.
// Разрешённое поле теряет исходный `ref`, поэтому суб-схема узнаётся по форме:
// вариантный узел — транспорты, объект с полями — по имени поля.
func refPage(name string, f *registry.Field) (string, bool) {
	if len(f.Variants) > 0 {
		return subPageFile["transports"], true
	}
	if f.Type != "object" || len(f.Fields) == 0 {
		return "", false
	}
	if file, ok := subPageFile[name]; ok {
		return file, true
	}
	return "", false
}

func nonEmpty(items ...string) []string {
	out := make([]string, 0, len(items))
	for _, s := range items {
		if strings.TrimSpace(s) != "" {
			out = append(out, s)
		}
	}
	return out
}

func trimFloat(v float64) string {
	if v == float64(int64(v)) {
		return strconv.FormatInt(int64(v), 10)
	}
	return strconv.FormatFloat(v, 'g', -1, 64)
}
