package main

import (
	"sort"
	"strconv"
	"strings"

	"singbox-launcher/core/config/registry"
)

// subPageFile — страница общей суб-схемы, на которую ссылается `ref` в теле.
// Имя файла начинается с подчёркивания: страница не принадлежит ни одной
// схеме, она общая.
var subPageFile = map[string]string{
	"tls":        "_tls.md",
	"transports": "_transports.md",
	"multiplex":  "_multiplex.md",
	"dialer":     "_dialer.md",
}

// renderScheme строит страницу одной схемы: шапка, таблица параметров ссылки,
// таблица полей тела. Обе таблицы несут по две колонки описания (EN | RU),
// чтобы страница была одна и языки не разъезжались.
func renderScheme(raw *rawRegistry, scheme string, body *registry.BodySchema) string {
	p := raw.protocols[scheme]
	var b strings.Builder

	title := scheme
	if p != nil && p.SingboxType != "" && p.SingboxType != scheme {
		title = scheme + " → " + p.SingboxType
	}
	b.WriteString("# " + title + "\n\n")
	b.WriteString("<!-- Сгенерировано contract/tools/gendocs. Не редактировать руками: правьте реестр. -->\n")
	b.WriteString("<!-- Generated by contract/tools/gendocs. Do not edit: change the registry instead. -->\n\n")
	b.WriteString("[← оглавление / index](../index.md) · [коды / warning codes](../warnings.md)\n\n")

	renderSchemeHeader(&b, p, body)
	renderURITable(&b, raw, p)
	renderBodyTable(&b, scheme, body)
	renderDegrade(&b, p)
	return b.String()
}

func renderSchemeHeader(b *strings.Builder, p *rawProtocol, body *registry.BodySchema) {
	t := &table{head: []string{"Поле / field", "Значение / value"}}
	if p == nil {
		t.add("scheme", "—")
		t.render(b)
		return
	}
	t.add("`scheme`", code(p.Scheme))
	t.add("`singbox_type`", code(p.SingboxType))
	t.add("`kind`", code(p.Kind))
	if len(p.Aliases) > 0 {
		t.add("`aliases`", codeList(p.Aliases))
	}
	if len(p.Sources) > 0 {
		t.add("`sources`", codeList(p.Sources))
	}
	ext := "—"
	if p.Extension != nil {
		ext = code(*p.Extension)
	}
	t.add("`extension`", ext)
	if body != nil && body.Core != "" {
		t.add("`body.core`", code(body.Core))
	}
	if p.URI != nil && p.URI.Fragment != "" {
		t.add("URI fragment", code(p.URI.Fragment))
	}
	t.render(b)

	if p.Note != "" {
		b.WriteString("> " + mdCell(p.Note) + "\n\n")
	}
}

// renderURITable — параметры ссылки: userinfo и uri.query.*. Общие параметры
// (TLS, REALITY, транспорты) живут не в схеме, а в суб-схемах, поэтому
// таблица завершается ссылками на их страницы.
func renderURITable(b *strings.Builder, raw *rawRegistry, p *rawProtocol) {
	if p == nil || p.URI == nil {
		b.WriteString("## Параметры ссылки / Link parameters\n\n")
		b.WriteString("Схема ссылкой не задаётся — только из sing-box JSON.\n")
		b.WriteString("_The scheme has no link form: it comes from sing-box JSON only._\n\n")
		return
	}
	b.WriteString("## Параметры ссылки / Link parameters\n\n")

	t := &table{head: []string{
		"Параметр / param", "Алиасы / aliases", "Тип, значения / type, values",
		"Дефолт / default", "`maps_to` → путь тела", "EN", "RU",
	}}
	if p.URI.Userinfo != nil {
		addURIRow(t, "userinfo", p.URI.Userinfo)
	}
	for _, name := range p.URI.queryOrder {
		if param := p.URI.Query[name]; param != nil {
			addURIRow(t, name, param)
		}
	}
	t.render(b)

	if len(t.rows) == 0 {
		b.WriteString("У схемы нет собственных query-параметров.\n")
		b.WriteString("_The scheme carries no query parameters of its own._\n\n")
	}
	b.WriteString("Общие параметры ссылки — на отдельных страницах: " +
		"[TLS / REALITY](_tls.md#параметры-ссылки--link-parameters), " +
		"[транспорты / transports](_transports.md).\n\n")
}

func addURIRow(t *table, name string, p *uriParam) {
	typ := p.Type
	if len(p.Values) > 0 {
		typ = strings.TrimSpace(typ + " " + codeList(p.Values))
	}
	if p.Allowlist != "" {
		typ = strings.TrimSpace(typ + " (allowlist `" + p.Allowlist + "`)")
	}
	if p.Meaning != "" && typ == "" {
		typ = code(p.Meaning)
	}
	if p.Validation != "" {
		typ = strings.TrimSpace(typ + " — " + p.Validation)
	}

	mapsTo := "—"
	if paths := p.mapsToPaths(); len(paths) > 0 {
		mapsTo = codeList(paths)
	}
	if p.DropAlways {
		mapsTo = "снимается всегда / always dropped"
	}

	label := code(name)
	if p.Ext != "" {
		label += " (" + p.Ext + ")"
	}
	t.add(label, codeList(p.Aliases), typ, scalar(p.Default), mapsTo, p.DescEn, p.DescRu)
}

// renderBodyTable — поля тела в порядке body.order. Ссылочные поля (`ref`)
// не разворачиваются на странице схемы: их правила общие, и дублировать их у
// каждой схемы значит завести 16 копий одной таблицы.
func renderBodyTable(b *strings.Builder, scheme string, body *registry.BodySchema) {
	b.WriteString("## Поля тела / Body fields\n\n")
	if body == nil {
		b.WriteString("Схема тела в реестре не описана (`body` отсутствует).\n")
		b.WriteString("_No body schema in the registry._\n\n")
		return
	}
	t := newBodyTable()
	for _, name := range body.Order {
		f := body.Fields[name]
		if f == nil {
			continue
		}
		if file, ok := refPage(name, f); ok {
			t.add(code(name), "ref", "см. / see ["+file+"]("+file+")", "", "", "", "", f.DescEn, f.DescRu)
			continue
		}
		addBodyRows(t, "", name, f, "../")
	}
	t.render(b)
	b.WriteString("Путь поля — как в теле узла; `on_invalid` говорит, что делает " +
		"санитайзер с негодным значением, код ведёт на [warnings.md](../warnings.md).\n")
	b.WriteString("_The path is the one used in the node body; `on_invalid` says what the " +
		"sanitizer does with a bad value, and the code links to [warnings.md](../warnings.md)._\n\n")
}

func newBodyTable() *table {
	return &table{head: []string{
		"Путь / path", "Тип / type", "Значения, формат, диапазон / values, format, range",
		"Дефолт / default", "Обяз. / req.", "Мусор / on invalid",
		"Гейт / gate", "EN", "RU",
	}}
}

// addBodyRows печатает поле и, для вложенных объектов и вариантов, его
// потомков отдельными строками с полным путём.
func addBodyRows(t *table, prefix, name string, f *registry.Field, linkPrefix string) {
	path := name
	if prefix != "" {
		path = prefix + "." + name
	}
	t.add(code(path), bodyType(f), bodyConstraints(f), scalar(f.Default),
		yesNo(f.Required), bodyOnInvalid(f, linkPrefix), bodyGate(f), f.DescEn, f.DescRu)

	if len(f.Variants) > 0 {
		names := make([]string, 0, len(f.Variants))
		for v := range f.Variants {
			names = append(names, v)
		}
		sort.Strings(names)
		for _, v := range names {
			addNested(t, path+"."+v, f.Variants[v], linkPrefix)
		}
		return
	}
	addNested(t, path, f, linkPrefix)
}

func addNested(t *table, path string, f *registry.Field, linkPrefix string) {
	inner := f
	if len(inner.Fields) == 0 && inner.Items != nil {
		inner = inner.Items
	}
	if len(inner.Fields) == 0 {
		return
	}
	order := inner.Order
	if len(order) == 0 {
		for k := range inner.Fields {
			order = append(order, k)
		}
		sort.Strings(order)
	}
	for _, name := range order {
		child := inner.Fields[name]
		if child == nil {
			continue
		}
		addBodyRows(t, path, name, child, linkPrefix)
	}
}

func bodyType(f *registry.Field) string {
	typ := f.Type
	if f.Discriminator != "" {
		typ += " (варианты по `" + f.Discriminator + "`)"
	}
	if f.Tristate {
		typ += ", tristate"
	}
	if f.Secret {
		typ += ", secret"
	}
	if f.Deprecated {
		typ += ", deprecated"
	}
	if f.Managed {
		typ += ", пишет сборка / set by config build"
	}
	if f.AllOrNothing {
		typ += ", all-or-nothing"
	}
	return typ
}

func bodyConstraints(f *registry.Field) string {
	var parts []string
	if len(f.Values) > 0 {
		parts = append(parts, scalarList(f.Values))
	}
	if f.Format != "" {
		parts = append(parts, "формат / format "+code(f.Format))
	}
	if f.Min != nil || f.Max != nil {
		lo, hi := "…", "…"
		if f.Min != nil {
			lo = trimFloat(*f.Min)
		}
		if f.Max != nil {
			hi = trimFloat(*f.Max)
		}
		parts = append(parts, code(lo+"–"+hi))
	}
	if f.Len != nil {
		parts = append(parts, "len "+code(strconv.Itoa(*f.Len)))
	}
	if f.LenParity != "" {
		parts = append(parts, "len "+code(f.LenParity))
	}
	if f.Normalize != "" {
		parts = append(parts, "normalize "+code(f.Normalize))
	}
	if f.Skip != "" {
		parts = append(parts, "skip: "+f.Skip)
	}
	return strings.Join(parts, "; ")
}

// bodyOnInvalid — что делают с негодным значением: действие санитайзера,
// информационные коды (advisory), запреты по схеме и связи между полями.
func bodyOnInvalid(f *registry.Field, linkPrefix string) string {
	var parts []string
	if f.OnInvalid != nil {
		act := f.OnInvalid.Action
		if act == "coerce" && f.OnInvalid.Value != nil {
			act += " → " + scalar(f.OnInvalid.Value)
		}
		parts = append(parts, act+" "+warnLink(f.OnInvalid.Code, linkPrefix))
	}
	for _, a := range f.Advisory {
		parts = append(parts, "advisory "+scalarList(a.Values)+" "+warnLink(a.Code, linkPrefix))
	}
	if len(f.ForbiddenFor) > 0 {
		parts = append(parts, "запрещено / forbidden for "+codeList(f.ForbiddenFor)+" "+warnLink(f.Code, linkPrefix))
	}
	if len(f.AllowedFor) > 0 {
		parts = append(parts, "только / only for "+codeList(f.AllowedFor)+" "+warnLink(f.Code, linkPrefix))
	}
	for _, c := range f.Conflicts {
		parts = append(parts, "конфликт / conflicts "+code(c.With)+" "+warnLink(c.Code, linkPrefix))
	}
	for _, rq := range f.Requires {
		parts = append(parts, "требует / requires "+code(rq.Path)+" "+warnLink(rq.Code, linkPrefix))
	}
	if f.DropAlways {
		parts = append(parts, "снимается всегда / always dropped")
	}
	return strings.Join(parts, "; ")
}

func bodyGate(f *registry.Field) string {
	var parts []string
	if f.MinCore != "" {
		parts = append(parts, "ядро / core ≥ "+code(f.MinCore))
	}
	if f.LxOnly {
		parts = append(parts, "только форк lx / lx fork only")
	}
	if f.BuildTag != "" {
		parts = append(parts, "тег / tag "+code(f.BuildTag))
	}
	if f.Platform != "" {
		parts = append(parts, "ОС / OS "+code(f.Platform))
	}
	return strings.Join(parts, "; ")
}

// refPage говорит, есть ли у ссылочного поля собственная страница.
// Разрешённое поле теряет исходный `ref`, поэтому суб-схема узнаётся по форме:
// вариантный узел — транспорты, объект с полями — по имени поля.
func refPage(name string, f *registry.Field) (string, bool) {
	if len(f.Variants) > 0 {
		return subPageFile["transports"], true
	}
	if f.Type != "object" || len(f.Fields) == 0 {
		return "", false
	}
	if file, ok := subPageFile[name]; ok {
		return file, true
	}
	return "", false
}

func renderDegrade(b *strings.Builder, p *rawProtocol) {
	if p == nil || len(p.Degrade) == 0 {
		return
	}
	b.WriteString("## Деградация / Degradation\n\n")
	for _, d := range p.Degrade {
		b.WriteString("- " + mdCell(d) + "\n")
	}
	b.WriteString("\n")
}

func yesNo(v bool) string {
	if v {
		return "да / yes"
	}
	return ""
}

func trimFloat(v float64) string {
	if v == float64(int64(v)) {
		return strconv.FormatInt(int64(v), 10)
	}
	return strconv.FormatFloat(v, 'g', -1, 64)
}
