package main

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"singbox-launcher/contract"
	"singbox-launcher/core/config/registry"
)

// subPage — страница общей суб-схемы (tls / transports / multiplex / dialer).
// Схема протокола ссылается на неё строкой «tls → см. _tls.md», а правила
// лежат здесь в одном экземпляре.
type subPage struct {
	file  string
	title string
	body  string
}

func (s *subPage) render() string { return s.body }

func subSchemaPages(raw *rawRegistry) []*subPage {
	names := []string{"dialer", "multiplex", "tls", "transports"}
	out := make([]*subPage, 0, len(names))
	for _, name := range names {
		page, err := renderSubSchema(raw, name)
		if err != nil {
			// Суб-схема обязана читаться: без неё не собирается ни одна схема.
			panic(fmt.Sprintf("gendocs: %s: %v", name, err))
		}
		out = append(out, page)
	}
	return out
}

// subFile — секции суб-схемы, как они лежат на диске. Загрузчик лаунчера
// отдаёт суб-схемы только уже разрешёнными внутрь схемы протокола (у него нет
// и не должно быть публичного «дай мне tls.json целиком»), поэтому для
// отдельной страницы файл читается здесь напрямую — теми же структурами
// registry.Field, то есть без второго словаря атрибутов.
type subFile struct {
	Body struct {
		Core          string                        `json:"core"`
		Order         []string                      `json:"order"`
		Fields        map[string]*registry.Field    `json:"fields"`
		Skipped       map[string]string             `json:"skipped"`
		Note          string                        `json:"note"`
		Discriminator string                        `json:"discriminator"`
		Values        []string                      `json:"values"`
		Variants      map[string]*subVariantSection `json:"variants"`
	} `json:"body"`
	Common *struct {
		Core   string                     `json:"core"`
		Order  []string                   `json:"order"`
		Fields map[string]*registry.Field `json:"fields"`
	} `json:"common"`
	Note string `json:"note"`
}

type subVariantSection struct {
	Order    []string                   `json:"order"`
	Fields   map[string]*registry.Field `json:"fields"`
	LxOnly   bool                       `json:"lx_only"`
	MinCore  string                     `json:"min_core"`
	BuildTag string                     `json:"build_tag"`
	Note     string                     `json:"note"`
}

func renderSubSchema(raw *rawRegistry, name string) (*subPage, error) {
	data, err := contract.ReadRegistry(name + ".json")
	if err != nil {
		return nil, err
	}
	var f subFile
	if err := json.Unmarshal(data, &f); err != nil {
		return nil, err
	}

	var b strings.Builder
	b.WriteString("# " + name + "\n\n")
	b.WriteString("<!-- Сгенерировано contract/tools/gendocs. Не редактировать руками: правьте реестр. -->\n")
	b.WriteString("<!-- Generated by contract/tools/gendocs. Do not edit: change the registry instead. -->\n\n")
	b.WriteString("Общая суб-схема реестра (`contract/registry/" + name + ".json`): её поля " +
		"подставляются в тело каждой схемы, которая на неё ссылается.\n")
	b.WriteString("_A shared registry sub-schema: its fields are substituted into the body of " +
		"every scheme that refers to it._\n\n")
	b.WriteString("[← оглавление / index](../index.md) · [коды / warning codes](../warnings.md)\n\n")
	if f.Body.Core != "" {
		b.WriteString("Сверено с ядром / checked against core: `" + f.Body.Core + "`\n\n")
	}
	if f.Note != "" {
		b.WriteString("> " + mdCell(f.Note) + "\n\n")
	}

	// Параметры ссылки, если суб-схема их несёт (tls, transports).
	renderSubURI(&b, raw, name)

	if f.Common != nil {
		b.WriteString("## Общие поля / Common fields\n\n")
		t := newBodyTable()
		fillSection(t, f.Common.Order, f.Common.Fields)
		t.render(&b)
	}

	if len(f.Body.Variants) > 0 {
		b.WriteString("## Варианты / Variants\n\n")
		b.WriteString("Дискриминатор / discriminator: `" + f.Body.Discriminator + "` — " +
			codeList(f.Body.Values) + "\n\n")
		if f.Body.Note != "" {
			b.WriteString("> " + mdCell(f.Body.Note) + "\n\n")
		}
		vnames := make([]string, 0, len(f.Body.Variants))
		for v := range f.Body.Variants {
			vnames = append(vnames, v)
		}
		sort.Strings(vnames)
		for _, v := range vnames {
			variant := f.Body.Variants[v]
			b.WriteString("### `" + v + "`\n\n")
			if gate := variantGate(variant); gate != "" {
				b.WriteString(gate + "\n\n")
			}
			if variant.Note != "" {
				b.WriteString("> " + mdCell(variant.Note) + "\n\n")
			}
			t := newBodyTable()
			fillSection(t, variant.Order, variant.Fields)
			t.render(&b)
		}
	} else if len(f.Body.Fields) > 0 {
		b.WriteString("## Поля тела / Body fields\n\n")
		if f.Body.Note != "" {
			b.WriteString("> " + mdCell(f.Body.Note) + "\n\n")
		}
		t := newBodyTable()
		fillSection(t, f.Body.Order, f.Body.Fields)
		t.render(&b)
	}

	if len(f.Body.Skipped) > 0 {
		b.WriteString("## Не описано намеренно / Deliberately not described\n\n")
		t := &table{head: []string{"Поле / field", "Причина / reason"}}
		keys := make([]string, 0, len(f.Body.Skipped))
		for k := range f.Body.Skipped {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			t.add(code(k), f.Body.Skipped[k])
		}
		t.render(&b)
	}

	return &subPage{file: subPageFile[name], title: name, body: b.String()}, nil
}

func fillSection(t *table, order []string, fields map[string]*registry.Field) {
	if len(order) == 0 {
		for k := range fields {
			order = append(order, k)
		}
		sort.Strings(order)
	}
	for _, name := range order {
		f := fields[name]
		if f == nil {
			continue
		}
		addBodyRows(t, "", name, f, "../")
	}
}

func variantGate(v *subVariantSection) string {
	var parts []string
	if v.MinCore != "" {
		parts = append(parts, "ядро / core ≥ `"+v.MinCore+"`")
	}
	if v.LxOnly {
		parts = append(parts, "только форк lx / lx fork only")
	}
	if v.BuildTag != "" {
		parts = append(parts, "тег сборки / build tag `"+v.BuildTag+"`")
	}
	if len(parts) == 0 {
		return ""
	}
	return "**" + strings.Join(parts, " · ") + "**"
}

// renderSubURI печатает параметры ссылки, которые лежат в суб-схеме: TLS и
// REALITY у tls.json, семейства транспортов у transports.json. Эти параметры
// общие для всех схем, поэтому в таблицах самих схем их нет.
func renderSubURI(b *strings.Builder, raw *rawRegistry, name string) {
	switch name {
	case "tls":
		b.WriteString("## Параметры ссылки / Link parameters\n\n")
		t := newURITable()
		for _, k := range raw.tlsOrder {
			if p := raw.tlsParams[k]; p != nil {
				addURIRow(t, k, p)
			}
		}
		for _, k := range raw.realityOrder {
			if p := raw.realityParams[k]; p != nil {
				addURIRow(t, k, p)
			}
		}
		t.render(b)
	case "transports":
		b.WriteString("## Параметры ссылки / Link parameters\n\n")
		for _, tname := range raw.transportOrder {
			tr := raw.transports[tname]
			if tr == nil {
				continue
			}
			b.WriteString("**`" + tname + "`**")
			if tr.SingboxType != "" && tr.SingboxType != tname {
				b.WriteString(" → `" + tr.SingboxType + "`")
			}
			b.WriteString("\n\n")
			t := newURITable()
			for _, k := range tr.paramOrder {
				if p := tr.Params[k]; p != nil {
					addURIRow(t, k, p)
				}
			}
			t.render(b)
		}
	}
}

func newURITable() *table {
	return &table{head: []string{
		"Параметр / param", "Алиасы / aliases", "Тип, значения / type, values",
		"Дефолт / default", "`maps_to` → путь тела", "EN", "RU",
	}}
}
