package main

import (
	"encoding/json"
	"sort"
	"strings"

	"singbox-launcher/contract"
	"singbox-launcher/core/config/registry"
)

// usage — одно место, где код может возникнуть: схема (или суб-схема) и путь
// поля. Собирается обходом всех body-секций реестра.
type usage struct {
	scheme string
	path   string
	via    string // on_invalid | advisory | conflicts | requires | allowed_for/forbidden_for
}

// renderWarnings строит warnings.md: по коду — якорь, severity, заголовки и
// тексты на двух языках, параметры и обратный индекс «где возникает».
//
// Обратный индекс — единственное, чего в реестре нет в готовом виде: реестр
// хранит ссылку поле→код, а человеку нужна ссылка код→поля. Он собирается
// обходом body-секций всех файлов; код, на который не ссылается ни одно поле,
// помечается как код уровня узла/подписки.
func renderWarnings(raw *rawRegistry, reg *registry.Registry) string {
	index := buildUsageIndex()

	codes := warningCodes()
	var b strings.Builder
	b.WriteString("# Коды предупреждений / Warning codes\n\n")
	b.WriteString("<!-- Сгенерировано contract/tools/gendocs. Не редактировать руками: правьте реестр. -->\n")
	b.WriteString("<!-- Generated by contract/tools/gendocs. Do not edit: change the registry instead. -->\n\n")
	b.WriteString("Словарь `contract/registry/warnings.json` — общий с LxBox: оба приложения " +
		"называют одно и то же событие одним кодом.\n")
	b.WriteString("_The `contract/registry/warnings.json` dictionary is shared with LxBox: both " +
		"apps report the same event under the same name._\n\n")
	b.WriteString("`severity: error` — узел отброшен целиком; `warning` и `info` остаются " +
		"на выжившем узле.\n")
	b.WriteString("_`severity: error` means the node was dropped; `warning` and `info` stay on a " +
		"surviving node._\n\n")
	b.WriteString("[← оглавление / index](index.md)\n\n")

	b.WriteString("## Список / Contents\n\n")
	t := &table{head: []string{"Код / code", "severity", "EN", "RU"}}
	for _, c := range codes {
		w, ok := reg.Warning(c)
		if !ok {
			continue
		}
		t.add("[`"+c+"`](#"+c+")", w.Severity, w.TitleEn, w.TitleRu)
	}
	t.render(&b)

	for _, c := range codes {
		w, ok := reg.Warning(c)
		if !ok {
			continue
		}
		b.WriteString("<a id=\"" + c + "\"></a>\n")
		b.WriteString("### " + c + "\n\n")
		b.WriteString("**severity:** `" + w.Severity + "`")
		if len(w.Params) > 0 {
			b.WriteString(" · **params:** " + codeList(w.Params))
		}
		b.WriteString("\n\n")
		if w.TitleEn != "" {
			b.WriteString("**EN — " + w.TitleEn + "**  \n")
			b.WriteString(oneLine(w.TextEn) + "\n\n")
		}
		if w.TitleRu != "" {
			b.WriteString("**RU — " + w.TitleRu + "**  \n")
			b.WriteString(oneLine(w.TextRu) + "\n\n")
		}
		writeUsages(&b, index[c])
	}
	return b.String()
}

func writeUsages(b *strings.Builder, list []usage) {
	b.WriteString("_Где возникает / where it comes from:_\n\n")
	if len(list) == 0 {
		b.WriteString("- уровень узла или подписки — код ставится не правилом поля " +
			"(no field in the registry points at this code: it is raised at node or " +
			"subscription level)\n\n")
		return
	}
	t := &table{head: []string{"Схема / scheme", "Путь / path", "Правило / rule"}}
	for _, u := range list {
		t.add(code(u.scheme), code(u.path), u.via)
	}
	t.render(b)
}

// buildUsageIndex обходит body-секции всех файлов реестра и собирает, какое
// поле на какой код ссылается. Обход идёт по сырым файлам, а не по
// разрешённой схеме: иначе поле суб-схемы попало бы в индекс 16 раз — по разу
// на каждую схему, которая её подставляет.
func buildUsageIndex() map[string][]usage {
	out := map[string][]usage{}

	files := []string{"tls.json", "transports.json", "multiplex.json", "dialer.json"}
	entries, err := contract.Registry.ReadDir("registry/protocols")
	if err == nil {
		names := make([]string, 0, len(entries))
		for _, e := range entries {
			if !e.IsDir() && strings.HasSuffix(e.Name(), ".json") {
				names = append(names, "protocols/"+e.Name())
			}
		}
		sort.Strings(names)
		files = append(files, names...)
	}
	sort.Strings(files)

	for _, name := range files {
		data, err := contract.ReadRegistry(name)
		if err != nil {
			continue
		}
		var f struct {
			Body   *rawSection `json:"body"`
			Common *rawSection `json:"common"`
		}
		if err := json.Unmarshal(data, &f); err != nil {
			continue
		}
		scheme := strings.TrimSuffix(strings.TrimPrefix(name, "protocols/"), ".json")
		for _, sec := range []*rawSection{f.Body, f.Common} {
			if sec == nil {
				continue
			}
			walkSection(out, scheme, "", sec)
		}
	}

	for c := range out {
		list := out[c]
		sort.SliceStable(list, func(i, j int) bool {
			if list[i].scheme != list[j].scheme {
				return list[i].scheme < list[j].scheme
			}
			if list[i].path != list[j].path {
				return list[i].path < list[j].path
			}
			return list[i].via < list[j].via
		})
		out[c] = list
	}
	return out
}

type rawSection struct {
	Order    []string                   `json:"order"`
	Fields   map[string]*registry.Field `json:"fields"`
	Variants map[string]*rawSection     `json:"variants"`
}

func walkSection(out map[string][]usage, scheme, prefix string, sec *rawSection) {
	names := sec.Order
	if len(names) == 0 {
		for k := range sec.Fields {
			names = append(names, k)
		}
		sort.Strings(names)
	}
	for _, name := range names {
		if f := sec.Fields[name]; f != nil {
			walkField(out, scheme, joinPath(prefix, name), f)
		}
	}
	vnames := make([]string, 0, len(sec.Variants))
	for v := range sec.Variants {
		vnames = append(vnames, v)
	}
	sort.Strings(vnames)
	for _, v := range vnames {
		walkSection(out, scheme, joinPath(prefix, v), sec.Variants[v])
	}
}

func walkField(out map[string][]usage, scheme, path string, f *registry.Field) {
	add := func(code, via string) {
		if code == "" {
			return
		}
		out[code] = append(out[code], usage{scheme: scheme, path: path, via: via})
	}
	if f.OnInvalid != nil {
		add(f.OnInvalid.Code, "on_invalid: "+f.OnInvalid.Action)
	}
	for _, a := range f.Advisory {
		add(a.Code, "advisory "+scalarList(a.Values))
	}
	for _, c := range f.Conflicts {
		add(c.Code, "conflicts "+c.With)
	}
	for _, rq := range f.Requires {
		add(rq.Code, "requires "+rq.Path)
	}
	if f.ForbiddenWhen != nil {
		add(f.ForbiddenWhen.Code, "forbidden_when "+f.ForbiddenWhen.Path)
	}
	if len(f.ForbiddenFor) > 0 {
		add(f.Code, "forbidden_for "+strings.Join(f.ForbiddenFor, ", "))
	} else if len(f.AllowedFor) > 0 {
		add(f.Code, "allowed_for "+strings.Join(f.AllowedFor, ", "))
	} else if f.Code != "" {
		add(f.Code, "code")
	}

	inner := f
	if len(inner.Fields) == 0 && inner.Items != nil {
		inner = inner.Items
	}
	if len(inner.Fields) > 0 {
		names := inner.Order
		if len(names) == 0 {
			for k := range inner.Fields {
				names = append(names, k)
			}
			sort.Strings(names)
		}
		for _, name := range names {
			if child := inner.Fields[name]; child != nil {
				walkField(out, scheme, joinPath(path, name), child)
			}
		}
	}
}

func joinPath(prefix, name string) string {
	if prefix == "" {
		return name
	}
	return prefix + "." + name
}

// warningCodes — коды словаря в алфавитном порядке (в файле они лежат по
// смыслу, но для листания по якорям нужен предсказуемый список).
func warningCodes() []string {
	data, err := contract.ReadRegistry("warnings.json")
	if err != nil {
		return nil
	}
	var f struct {
		Warnings map[string]json.RawMessage `json:"warnings"`
	}
	if err := json.Unmarshal(data, &f); err != nil {
		return nil
	}
	out := make([]string, 0, len(f.Warnings))
	for k := range f.Warnings {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// oneLine схлопывает перевод строки внутри текста кода: шаблоны `{path}` и
// прочие подстановки остаются как есть — их подставляет приложение.
func oneLine(s string) string {
	s = strings.ReplaceAll(s, "\r\n", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.TrimSpace(s)
}
